_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 84
                - 86
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 84
                - 86
                - 98
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.10
            "6": 4.51.2
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
